#!/bin/bash

#sudo ./usr/lib/frr/frrinit.sh start
if [ -r "/lib/lsb/init-functions" ]; then
        . /lib/lsb/init-functions
else
        log_success_msg() {
                echo "$@"
        }
        log_warning_msg() {
                echo "$@" >&2
        }
        log_failure_msg() {
                echo "$@" >&2
        }
fi

source /usr/lib/frr/frrcommon.sh
echo  $(daemon_list)
sudo /usr/lib/frr/watchfrr $(daemon_list)

